[package]
name = "solana-account-constraints"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = ">=1.10.34"
thiserror = "1.0.34"
