[package]
name = "saf-macros"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true
test = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro3 = "0.1.1"
syn = "1.0.102"
quote = "1.0.21"
